luffy_permission/urls.py
from django.contrib import admin
from django.urls import path,re_path,include

urlpatterns = [
    path('admin/', admin.site.urls),  # 分发生成 RegexURLResolver
    re_path(r'rbac/', include(('rbac.urls','rbac'),namespace='rbac')), #分发生成 RegexURLResolver
    re_path(r'', include('web.urls')),  #分发生成 RegexURLResolver
    # path('/index',xxx)  # 分发 RegexURLPattern
    path('index/',lambda x: x*x)
]

rbac/service/urls.py
from django.http import QueryDict
from django.urls import reverse

def memory_url(request,name,*args,**kwargs):
    """
    生成带搜索条件的URL
    """
    basic_url = reverse(name,args=args,kwargs=kwargs)

    #当前URL 无参数
    if not request.GET:
        return basic_url

    query_dict = QueryDict(mutable=True)
    query_dict['_filter'] = request.GET.urlencode()  #把URL参数复制

    return '%s?%s' %(basic_url,query_dict.urlencode())


def memory_reverse(request,name,*args,**kwargs):
    url = reverse(name,args=args,kwargs=kwargs)
    orgin_params = request.GET.get('_filter')
    if orgin_params:
        url = '%s?%s' % (url, orgin_params)

    return url

rbac/urls.py
from django.conf.urls import url
from rbac.views import role,user,menu

urlpatterns = [
    url(r'^role/list/$', role.role_list,name='role_list'),
    url(r'^role/add/$', role.role_add,name='role_add'),
    url((r'^role/edit/(?P<rid>\d+)/$'),role.role_edit,name='role_edit'),
    url(r'^role/del/(?P<rid>\d+)/$',role.role_del,name='role_del'),

    url(r'^user/list/$', user.user_list,name='user_list'),
    url(r'^user/add/$', user.user_add,name='user_add'),
    url((r'^user/edit/(?P<rid>\d+)/$'),user.user_edit,name='user_edit'),
    url(r'^user/del/(?P<rid>\d+)/$',user.user_del,name='user_del'),
    url(r'^user/resetpwd/(?P<rid>\d+)/$',user.user_resetpwd,name='user_resetpwd'),

    url(r'^menu/list/$',menu.menu_list,name='menu_list'),
    url(r'^menu/add/$',menu.menu_add,name='menu_add'),
    url(r'^menu/edit/(?P<mid>\d+)/$',menu.menu_edit,name='menu_edit'),
    url(r'^menu/del/(?P<mid>\d+)/$',menu.menu_del,name='menu_del'),

    url(r'^smenu/add/$',menu.smenu_add,name='smenu_add'),
    url(r'^smenu/edit/(?P<pid>\d+)/$',menu.smenu_edit,name='smenu_edit'),
    url(r'^smenu/del/(?P<pid>\d+)/$',menu.smenu_del,name='smenu_del'),

    url(r'^pmenu/add/$',menu.pmenu_add,name='pmenu_add'),
    url(r'^pmenu/edit/(?P<pid>\d+)/$',menu.pmenu_edit,name='pmenu_edit'),
    url(r'^pmenu/del/(?P<pid>\d+)/$',menu.pmenu_del,name='pmenu_del'),

    url(r'^multi/pmenu/$',menu.multi_pmenu,name='multi_pmenu'),
    url(r'^multi/pmenu/del/(?P<pk>\d+)$',menu.multi_pmenu_del,name='multi_pmenu_del'),

    url(r'^distribute/pmenu',menu.distribute_pmenu,name='distribute_pmenu')


]

web/urls.py
from django.conf.urls import url
from web.views import customer
from web.views import payment
from web.views import account

urlpatterns = [
    url(r'^customer/list/$', customer.customer_list,name='customer_list'),
    url(r'^customer/add/$', customer.customer_add),
    url(r'^customer/edit/(?P<cid>\d+)/$', customer.customer_edit,name='customer_edit'),
    url(r'^customer/del/(?P<cid>\d+)/$', customer.customer_del,name='customer_del'),
    url(r'^customer/import/$', customer.customer_import,name='customer_import'),
    url(r'^customer/tpl/$', customer.customer_tpl,name='customer_tpl'),

    url(r'^payment/list/$', payment.payment_list,name='payment_list'),
    url(r'^payment/add/$', payment.payment_add,name='payment_add'),
    url(r'^payment/edit/(?P<pid>\d+)/$', payment.payment_edit,name='payment_edit'),
    url(r'^payment/del/(?P<pid>\d+)/$', payment.payment_del,name='payment_del'),

    url(r'^login/$', account.login),

]

rbac/forms/base.py
from django.forms import ModelForm
from django import forms
class BaseModelForm(ModelForm):
    exclude_bootstrap = []
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        #自定义功能
        for k,field in self.fields.items():
            if k in self.exclude_bootstrap:
                continue
            if k == 'password':
                field.widget = forms.PasswordInput()
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

rbac/forms/role.py
from rbac.forms.base import BaseModelForm
from rbac.models import Role

class RoleModelForm(BaseModelForm):

    class Meta:
        model = Role
        fields = ['title']
        # fields = '__all__'

rbac/views/menu.py
import datetime
from collections import OrderedDict

from django.forms import formset_factory
from django.shortcuts import render, redirect, reverse, HttpResponse
from rbac.forms.memu import MenuModelForm, SmenuModelForm, PmenuModelForm, MultiAddPermissionForm, \
    MultiEditPermissionForm
from rbac.models import Menu, Permission, UserInfo, Role
from rbac.service.route import get_all_url_dict
from rbac.service.urls import memory_reverse
from django.http import QueryDict


def menu_list(request):
    menus = Menu.objects.all()
    second_menus = []
    permission_menus = []
    menu_id = request.GET.get('mid')
    smenu_id = request.GET.get('smid')
    pmenu_id = request.GET.get('pmid')
    if menu_id:
        mobj = Menu.objects.filter(pk=menu_id)
        second_menus = Permission.objects.filter(menu_id=menu_id)
        if not mobj:
            menu_id = None

    if smenu_id:
        sobj = Permission.objects.filter(pk=smenu_id)
        permission_menus = Permission.objects.filter(pid_id=smenu_id)
        if not sobj:
            smenu_id = None

    if pmenu_id:
        pobj = Permission.objects.get(pk=pmenu_id)

    return render(request, 'rbac/menu_list.html',
                  {"menus": menus, "menu_id": menu_id, "second_menus": second_menus, "smenu_id": smenu_id,
                   "permission_menus": permission_menus, "pmenu_id": pmenu_id})


def menu_add(request):
    form = MenuModelForm()

    if request.method == 'POST':
        form = MenuModelForm(data=request.POST)
        if form.is_valid():
            form.save()
            url = memory_reverse(request, 'rbac:menu_list')

            return redirect(url)
    return render(request, 'rbac/change_menu.html', {"form": form})


def menu_edit(request, mid):
    mobj = Menu.objects.get(pk=mid)
    if not mobj:
        return HttpResponse("菜单不存在")
    form = MenuModelForm(instance=mobj)
    if request.method == 'POST':
        form = MenuModelForm(request.POST, instance=mobj)
        if form.is_valid():
            form.save()
            url = memory_reverse(request, 'rbac:menu_list')
            return redirect(url)
    return render(request, 'rbac/change_menu.html', {"form": form})


def menu_del(request, mid):
    url = memory_reverse(request, 'rbac:menu_list')

    if request.method == 'POST':
        try:
            Menu.objects.filter(pk=mid).delete()
            return redirect(url)
        except:
            return HttpResponse("删除失败")

    return render(request, 'rbac/delete.html', {"cancel_url": url})


def smenu_add(request):
    orgin_params = request.GET.get('_filter')
    params_dict = QueryDict(orgin_params)

    mobj = Menu.objects.get(pk=params_dict['mid'])
    form = SmenuModelForm()

    if request.method == 'POST':
        form = SmenuModelForm(data=request.POST)
        if form.is_valid():
            form.instance.menu = mobj
            form.save()
            url = memory_reverse(request, 'rbac:menu_list')

            return redirect(url)
    return render(request, 'rbac/change_menu.html', {"form": form})


def smenu_edit(request, pid):
    pobj = Permission.objects.get(pk=pid)
    if not pobj:
        return HttpResponse("菜单不存在")
    form = SmenuModelForm(instance=pobj)
    if request.method == 'POST':
        form = SmenuModelForm(data=request.POST,instance=pobj)
        if form.is_valid():
            form.save()
            url = memory_reverse(request, 'rbac:menu_list')
            return redirect(url)
    return render(request, 'rbac/change_menu.html', {"form": form})


def smenu_del(request, pid):
    url = memory_reverse(request, 'rbac:menu_list')

    if request.method == 'POST':
        try:
            Permission.objects.filter(pk=pid).delete()
            return redirect(url)
        except:
            return HttpResponse("删除失败")

    return render(request, 'rbac/delete.html', {"cancel_url": url})

#权限管理
def pmenu_add(request):
    orgin_params = request.GET.get('_filter')
    params_dict = QueryDict(orgin_params)

    pobj = Permission.objects.get(pk=params_dict['smid'])
    if not pobj:
        return HttpResponse("权限不存在")
    form = PmenuModelForm()
    if request.method == 'POST':
        form = PmenuModelForm(data=request.POST)
        if form.is_valid():
            form.instance.pid = pobj
            form.save()
            url = memory_reverse(request, 'rbac:menu_list')

            return redirect(url)
    return render(request, 'rbac/change_menu.html', {"form": form})


def pmenu_edit(request, pid):
    pobj = Permission.objects.get(pk=pid)
    if not pobj:
        return HttpResponse("菜单不存在")
    form = PmenuModelForm(instance=pobj)
    if request.method == 'POST':
        form = PmenuModelForm(data=request.POST,instance=pobj)
        if form.is_valid():
            form.save()
            url = memory_reverse(request, 'rbac:menu_list')
            return redirect(url)
    return render(request, 'rbac/change_menu.html', {"form": form})


def pmenu_del(request, pid):
    url = memory_reverse(request, 'rbac:menu_list')

    if request.method == 'POST':
        try:
            Permission.objects.filter(pk=pid).delete()
            return redirect(url)
        except:
            return HttpResponse("删除失败")

    return render(request, 'rbac/delete.html', {"cancel_url": url})


def multi_pmenu(request):
    """
    批量操作权限
    """
    generate_formset_class = formset_factory(MultiAddPermissionForm, extra=0)
    update_formset_class = formset_factory(MultiEditPermissionForm, extra=0)

    post_type = request.GET.get('type')
    generate_formset = None
    update_formset = None
    if request.method == 'POST' and post_type == 'generate':
        # pass  #批量添加
        formset = generate_formset_class(data=request.POST)
        if formset.is_valid():
            object_list = []
            post_row_list = formset.cleaned_data
            has_error = False
            for i in range(0,formset.total_form_count()):
                row_dict = post_row_list[i]
                print(row_dict)
                try:
                    new_object = Permission(**row_dict)
                    new_object.validate_unique()
                    object_list.append(new_object)
                except Exception as e:
                    formset.errors[i].update(e)
                    generate_formset = formset
                    has_error = True
            if not has_error:
                Permission.objects.bulk_create(object_list,batch_size=100)
        else:
            generate_formset = formset

    if request.method == 'POST' and post_type == 'update':
        # pass  #批量更新
        formset = update_formset_class(data=request.POST)
        if formset.is_valid():
            post_row_list = formset.cleaned_data
            for i in range(0,formset.total_form_count()):
                row_dict = post_row_list[i]
                permission_id = row_dict.pop('id')
                try:
                    row_object = Permission.objects.filter(id=permission_id).first()
                    for k,v in row_dict.items():
                        setattr(row_object,k,v)
                    row_object.validate_unique()
                    row_object.save()
                except Exception as e:
                    formset.errors[i].update(e)
                    update_formset = formset
        else:
            update_formset = formset

    #1.获取项目中所有的URL
    all_url_dict = get_all_url_dict()

    router_name_set = set(all_url_dict.keys())

    #2.获取数据库中所有的URL
    permissions = Permission.objects.all().values('id','title','url_name','url','menu_id','pid_id')
    permission_dict = OrderedDict()
    permission_name_set = set()

    for row in permissions:
        permission_dict[row['url_name']] = row
        permission_name_set.add(row['url_name'])


    #3. 应该添加，删除，修改的权限有哪些

    for name,value in permission_dict.items():
        route_row_dict = all_url_dict.get(name)
        if not route_row_dict:
            continue
        if value['url'] != route_row_dict['url']:
            value['url'] = '路由和数据库中不一致'

    #3.1计算出应该增加的name
    if not generate_formset:
        generate_name_list = router_name_set - permission_name_set
        generate_formset = generate_formset_class(initial=[ row_dict for name,row_dict in all_url_dict.items() if name in generate_name_list])


    #3.2 计算出需要删除的name
    delete_name_list = permission_name_set - router_name_set
    delete_row_list = [ row_dict for name,row_dict in permission_dict.items() if name in delete_name_list ]

    #3.3 计算出应该更新的name
    if not update_formset:
        update_name_list = permission_name_set & router_name_set
        update_formset = update_formset_class(initial=[ row_dict for name,row_dict in permission_dict.items() if name in update_name_list])

    return render(request,'rbac/multi_permissions.html',
                  {
                      "generate_formset": generate_formset,
                      "delete_row_list": delete_row_list,
                      "update_formset": update_formset,

                  })


def multi_pmenu_del(request,pk):
    url = memory_reverse(request,"rbac:multi_pmenu")
    if request.method == 'POST':
        Permission.objects.filter(id=pk).delete()
        return redirect(url)

    return render(request,'rbac/delete.html',{"cancel_url": url})


def distribute_pmenu(request):
    """
    权限分配
    :param request:
    :return:
    """

    user_id = request.GET.get('uid')
    user_object = UserInfo.objects.filter(id=user_id).first()
    if not user_object:
        user_id = None

    role_id = request.GET.get('rid')
    role_object = Role.objects.filter(id=role_id).first()
    if not role_object:
        role_id = None

    if request.method == 'POST' and request.POST.get('type') == 'role':
        role_id_list = request.POST.getlist('roles')
        # 用户和角色关系添加到第三张表（关系表）
        if not user_object:
            return HttpResponse('请选择用户，然后再分配角色！')
        user_object.roles.set(role_id_list)

rbac/views/role.py
from django.shortcuts import render,redirect,reverse,HttpResponse
from rbac.models import Role
from rbac.forms.role import RoleModelForm

def role_list(request):

    data_list = Role.objects.all()
    return render(request,'rbac/role_list.html',{"data_list": data_list})

def role_add(request):
    form = RoleModelForm()

    if request.method == 'POST':
        form = RoleModelForm(data=request.POST)
        if form.is_valid():
            form.save()
            url = reverse('rbac:role_list')
            return redirect(url)
    return render(request,'rbac/change.html',{"form": form})

def role_edit(request,rid):
    role_obj = Role.objects.get(pk=rid)
    form = RoleModelForm(instance=role_obj)
    if request.method == 'POST':
        form = RoleModelForm(data=request.POST,instance=role_obj)
        if form.is_valid():
            form.save()
            url = reverse('rbac:role_list')
            return redirect(url)
    return render(request,'rbac/change.html',{"form": form })


def role_del(request,rid):
    url = reverse('rbac:role_list')
    if request.method == 'GET':
        return render(request,'rbac/delete.html',{"cancel_url": url})
    try:
        Role.objects.filter(pk=rid).delete()
        return redirect(url)
    except:
        return HttpResponse("删除失败")

rbac/views/user.py
from django.shortcuts import render,redirect,reverse,HttpResponse
from rbac.models import UserInfo
from rbac.forms.user import UserInfoModelForm, UserInfoUpdateModelForm, UserInfoResetPwdModelForm


def user_list(request):

    data_list = UserInfo.objects.all()
    return render(request,'rbac/user_list.html',{"data_list": data_list})

def user_add(request):
    form = UserInfoModelForm()

    if request.method == 'POST':
        form = UserInfoModelForm(data=request.POST)
        if form.is_valid():
            form.save()
            url = reverse('rbac:user_list')
            return redirect(url)
    return render(request,'rbac/userchange.html',{"form": form})

def user_edit(request,rid):
    role_obj = UserInfo.objects.get(pk=rid)
    if not role_obj:
        return HttpResponse("用户不存在")
    form = UserInfoUpdateModelForm(instance=role_obj)
    if request.method == 'POST':
        form = UserInfoUpdateModelForm(data=request.POST,instance=role_obj)
        if form.is_valid():
            form.save()
            url = reverse('rbac:user_list')
            return redirect(url)
    return render(request,'rbac/userchange.html',{"form": form })


def user_del(request,rid):
    url = reverse('rbac:user_list')
    if request.method == 'GET':
        return render(request,'rbac/delete.html',{"cancel_url": url})
    try:
        UserInfo.objects.filter(pk=rid).delete()
        return redirect(url)
    except:
        return HttpResponse("删除失败")


def user_resetpwd(request,rid):
    url = reverse('rbac:user_list')
    user_obj = UserInfo.objects.get(pk=rid)
    if not user_obj:
        return HttpResponse("用户不存在")
    form = UserInfoResetPwdModelForm(instance=user_obj)
    if request.method == 'POST':
        form = UserInfoResetPwdModelForm(data=request.POST,instance=user_obj)
        if form.is_valid():
            form.save()
            return redirect(url)
    return render(request, 'rbac/userchange.html', {"form": form})

rbac/templates/rbac/breadcrumbnav.html
<div>
    <ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">
        {% for item in breadcrumb_nav_list %}
        {% if item.class %}
            <li class="active">{{item.title}}</li>
        {% else %}
            <li><a href="{{ item.url }}">{{ item.title }}</a></li>
        {% endif %}
        {% endfor %}
        <!-- <li><a href="#">首页</a></li>
        <li class="active">客户管理</li> -->

    </ol>
</div>

rbac/templates/rbac/change.html
{% extends 'layout.html' %}

{% block content %}
    <div class="luffy-container">
        <form class="form-horizontal clearfix" method="post" novalidate>
            {% csrf_token %}

            {% for field in form %}
                <div class="form-group col-sm-6 clearfix">
                    <label class="col-sm-3 control-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }} <span style="color:firebrick;">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group col-sm-12">
                <div class="col-sm-6">
                    <div class="col-sm-offset-3">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

rbac/templates/rbac/change_menu.html
{% extends 'layout.html' %}

{% block css %}
    <style>
        .icon-area ul {
            list-style-type: none;
            padding: 0;
        }

        .icon-area ul li {
            float: left;
            padding: 10px;
            width: 80px;
        }

        .icon-area ul li i {
            font-size: 18px;
            margin-left: 5px;
            color: #6d6565;
        }

    </style>
{% endblock %}

{% block content %}
    <div class="luffy-container">
        <form class="form-horizontal clearfix" method="post" novalidate>
            {% csrf_token %}

            {% for field in form %}
                <div class="form-group col-sm-7 clearfix" style="height: 38px;">
                    <label class="col-sm-3 control-label">{{ field.label }}</label>
                    <div class="col-sm-9 icon-area">
                        {{ field }}
                        <span style="color:firebrick;">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group col-sm-5 " style="margin-top: -50px;">
                <div class="col-sm-7">
                    <div class="col-sm-offset-1">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

rbac/templates/rbac/delete.html
{% extends 'layout.html' %}

{% block content %}
    <div class="luffy-container">
        <div class="alert alert-danger" role="alert">
            <form method="post">
                {% csrf_token %}
                <p style="font-size: 13px;"><i class="fa fa-warning" aria-hidden="true"></i> 删除后将不可恢复，请确认是否删除？</p>
                <div style="margin-top: 20px;">
                    <a href="{{ cancel_url}}" class="btn btn-default btn-sm">取消</a>
                    <button type="submit" class="btn btn-danger btn-sm">确  认</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

rbac/templates/rbac/multi_menu.html
<div class="multi-menu">
    <div class="item">
        {% for item in menu_dict.values %}
            <div class="title" id="multi-menu-item-title"><span class="icon-wrap"><i class="fa {{ item.icon }}"></i></span>  {{ item.title }}</div>
            <div class="multi-menu-item-body {{ item.class }}">
                {% for per in item.children %}
                    <a href="{{ per.url }}" class="{{ per.class }}">{{ per.title }}</a>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
</div>

rbac/templates/rbac/multi_permissions.html
{% extends 'layout.html' %}

{% block content %}
    <div class="luffy-container">
        <div class="bs-example" data-example-id="table-within-panel">
            <form method="post" action="?type=generate">
                {% csrf_token %}
                {{ generate_formset.management_form }}
                <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-th-list" aria-hidden="true"></i> 待新建权限列表
                    <button href="#" class="right btn btn-primary btn" style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-save" aria-hidden="true"></i> 新建</button>
                </div>


                <!-- Table -->
                <table class="table">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>名称</th>
                        <th>URL</th>
                        <th>别名</th>
                        <th>菜单</th>
                        <th>父权限</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for form in generate_formset %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                {% for field in form %}
                                <td>{{ field }}<span style="color: red;">{{ field.errors.0 }} </span></td>

                                {% endfor %}
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
            </form>

            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-th-list" aria-hidden="true"></i> 待删除权限列表
<!--                    <a href="#" class="right btn btn-primary btn" style="padding: 2px 8px;margin: -3px;">-->
<!--                        <i class="fa fa-plus-circle" aria-hidden="true"></i> 新建</a>-->
                </div>


                <!-- Table -->
                <table class="table">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>名称</th>
                        <th>URL</th>
                        <th>别名</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for row in delete_row_list %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ row.title }}</td>
                                <td>{{ row.url }}</td>
                                <td>{{ row.url_name }}</td>
                                <td> <a style="color: #d9534f;" href="{% url 'rbac:multi_pmenu_del' pk=row.id %}"><i
                                    class="fa fa-trash-o"></i></a> </td>

                            </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
            <form method="post" action="?type=update">
                {% csrf_token %}
                {{ update_formset.management_form }}
                <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-th-list" aria-hidden="true"></i> 待更新权限列表
                    <button href="#" class="right btn btn-primary btn" style="padding: 2px 8px;margin: -3px;">
                        <i class="fa fa-save" aria-hidden="true"></i> 更新</button>
                </div>


                <!-- Table -->
                <table class="table">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>名称</th>
                        <th>URL</th>
                        <th>别名</th>
                        <th>菜单</th>
                        <th>父权限</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for form in update_formset %}
                            <tr>
                                <td>{{ forloop.counter }}</td>

                                {% for field in form %}
                                {% if forloop.first %}
                                   {{ field }}
                                {% else %}
                                <td>{{ field }}<span style="color: red;">{{field.error.0}} </span></td>
                                {% endif %}

                                {% endfor %}
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
            </form>
        </div>

    </div>
{% endblock %}

rbac/templates/rbac/role_list.html
{% extends 'layout.html' %}
{% load rbac %}

{% block content %}
    <div class="luffy-container">
        <div style="margin: 5px 0;">
            {% if request|has_permission:'role_add' %}
            <a class="btn btn-success" href="{% url 'rbac:role_add' %}">
                <i class="fa fa-plus-square" aria-hidden="true"></i> 添加角色
            </a>
            {% endif %}
        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>ID</th>
                <th>角色名称</th>
                {% if request|has_permission:'role_edit' or request|has_permission:'role_del' %}
                <th>选项</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for row in data_list %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.title }}</td>
                    {% if request|has_permission:'role_edit' or request|has_permission:'role_del' %}
                    <td>
                        {% if request|has_permission:'role_edit' %}
                        <a style="color: #333333;" href="{% url 'rbac:role_edit' rid=row.id %}">
                            <i class="fa fa-edit" aria-hidden="true"></i></a>
                        {% endif %}
                        |
                        {% if request|has_permission:'role_del' %}
                        <a style="color: #d9534f;" href="{% url 'rbac:role_del' rid=row.id %}"><i class="fa fa-trash-o"></i></a>
                        {% endif %}
                    </td>
                     {% endif %}

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

rbac/templates/rbac/static_menu.html
<div class="static-menu">
               <!-- <a href="/customer/list/" class="active">
                    <span class="icon-wrap"><i class="fa fa-connectdevelop"></i></span> 客户管理</a>
                <a href="/payment/list/">
                    <span class="icon-wrap"><i class="fa fa-code-fork"></i></span> 账单管理</a>
                    -->
                {% for item in menu_list %}
                   <a href="{{ item.url }}">
                    <span class="icon-wrap"><i class="fa {{ item.icon }}"></i></span> {{ item.title }}</a>
                {% endfor %}
</div>

rbac/templates/rbac/user_list.html
{% extends 'layout.html' %}
{% load rbac %}

{% block content %}
    <div class="luffy-container">
        <div style="margin: 5px 0;">
            {% if request|has_permission:'user_add' %}
            <a class="btn btn-success" href="{% url 'rbac:user_add' %}">
                <i class="fa fa-plus-square" aria-hidden="true"></i> 添加用户
            </a>
            {% endif %}
        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>序号</th>
                <th>用户名</th>
                <th>邮箱</th>
                {% if request|has_permission:'user_resetpwd' %}
                <th>重置密码</th>
                {% endif %}
                {% if request|has_permission:'user_edit' or request|has_permission:'user_del' %}
                <th>选项</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for row in data_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ row.name }}</td>
                    <td>{{ row.email }}</td>
                    {% if request|has_permission:'user_resetpwd' %}
                    <td><a href="{% url 'rbac:user_resetpwd' rid=row.id %}">重置密码</a></td>
                    {% endif %}
                    {% if request|has_permission:'user_edit' or request|has_permission:'user_del' %}
                    <td>
                        {% if request|has_permission:'user_edit' %}
                        <a style="color: #333333;" href="{% url 'rbac:user_edit' rid=row.id %}">
                            <i class="fa fa-edit" aria-hidden="true"></i></a>
                        {% endif %}
                        |
                        {% if request|has_permission:'user_del' %}
                        <a style="color: #d9534f;" href="{% url 'rbac:user_del' rid=row.id %}"><i class="fa fa-trash-o"></i></a>
                        {% endif %}
                    </td>
                     {% endif %}

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}